services:
  _defaults:
    public: true
    autowire: true

  Fluxter\SaasProviderBundle\Service\SaasClientService:
    file: "@@SaasProviderBundle//Service/SaasClientService.php"

  Fluxter\SaasProviderBundle\EventSubscriber\:
    tags:
      - { name: kernel.event_subscriber }
  
